### ISSUE TITLE
InvalidArgumentError : No OpKernel was registered to support Op 'FarthestPointSample

### ISSUE THREAD

**Issue by hiwasawa0715** [intel-isl/Open3D-PointNet2-Semantic3D#54]
I tried to run "train.py"(process 5 train at "usage").
But, I get the following "InvalidArgumentError" error.
Please tell me how to deal with this problem.

[my environment]
ubuntu 16.04
cuda 9.0
cudnn 7.5.0
[anaconda3]
python 3.6
tensorflow 1.12.0
tensorflow-gpu 1.12.0
scikit-learn 0.21.3 
open3d-python 0.7.0.0

---------------------------------------------------------------------------------

tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'FarthestPointSample' with these attrs.  Registered devices: [CPU,XLA_CPU], Registered kernels:
  device='GPU'

	 [[{{node layer1/FarthestPointSample}} = FarthestPointSample[npoint=1024, _device="/device:GPU:0"](Slice)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 469, in <module>
    train()
  File "train.py", line 410, in train
    sess.run(tf.global_variables_initializer())
  File "/home/uname/anaconda3/envs/pointNet2_py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/uname/anaconda3/envs/pointNet2_py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/uname/anaconda3/envs/pointNet2_py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/uname/anaconda3/envs/pointNet2_py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'FarthestPointSample' with these attrs.  Registered devices: [CPU,XLA_CPU], Registered kernels:
  device='GPU'

	 [[node layer1/FarthestPointSample (defined at <string>:103)  = FarthestPointSample[npoint=1024, _device="/device:GPU:0"](Slice)]]

Caused by op 'layer1/FarthestPointSample', defined at:
  File "train.py", line 469, in <module>
    train()
  File "train.py", line 359, in train
    bn_decay=bn_decay,
  File "/home/uname/PointNet2/Open3D-PointNet2-Semantic3D-master/model.py", line 47, in get_model
    scope="layer1",
  File "/home/uname/PointNet2/Open3D-PointNet2-Semantic3D-master/util/pointnet_util.py", line 144, in pointnet_sa_module
    npoint, radius, nsample, xyz, points, knn, use_xyz
  File "/home/uname/PointNet2/Open3D-PointNet2-Semantic3D-master/util/pointnet_util.py", line 37, in sample_and_group
    xyz, farthest_point_sample(npoint, xyz)
  File "/home/uname/PointNet2/Open3D-PointNet2-Semantic3D-master/tf_ops/tf_sampling.py", line 69, in farthest_point_sample
    return sampling_module.farthest_point_sample(inp, npoint)
  File "<string>", line 103, in farthest_point_sample
  File "/home/uname/anaconda3/envs/pointNet2_py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/uname/anaconda3/envs/pointNet2_py36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/uname/anaconda3/envs/pointNet2_py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/uname/anaconda3/envs/pointNet2_py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'FarthestPointSample' with these attrs.  Registered devices: [CPU,XLA_CPU], Registered kernels:
  device='GPU'

	 [[node layer1/FarthestPointSample (defined at <string>:103)  = FarthestPointSample[npoint=1024, _device="/device:GPU:0"](Slice)]]

**Comment by windcatcher** [comment]
me too

**Comment by monroe-dev** [comment]
same error,

**Comment by ytyfeng** [comment]
Did you see if test_tf_ops.py worked?

**Comment by davidlmljll** [comment]
Hello,Is the problem solved?

**Comment by ali-mz** [comment]
same error

**Comment by asadabbas09** [comment]
any update? I'm also getting this error.

**Comment by Charlie-0118** [comment]
me too, anyone knows how to fix it?
