### ISSUE TITLE
test_tf_ops.py failed. libtf_grouping.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

### ISSUE THREAD

**Issue by ytyfeng** [intel-isl/Open3D-PointNet2-Semantic3D#59]
When I was building tf_ops, I was able to build all of those .so files. However, when I ran test_tf_ops.py, it gave me this error.
```
$ python tf_ops/test_tf_ops.py 
2020-02-14 17:46:28.741274: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "tf_ops/test_tf_ops.py", line 4, in <module>
    from tf_grouping import query_ball_point, group_point, knn_point
  File "/home/user/Open3D-PointNet2-Semantic3D/tf_ops/tf_grouping.py", line 9, in <module>
    os.path.join(BASE_DIR, "build", "libtf_grouping.so")
  File "/home/user/.conda/envs/my_env/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/user/Open3D-PointNet2-Semantic3D/tf_ops/build/libtf_grouping.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
```

**Comment by ytyfeng** [comment]
Was able to resolve this by removing the -D_GLIBCXX_USE_CXX11_ABI=0 flag in CMakeList.txt.
