### ISSUE TITLE
Down sampling error

### ISSUE THREAD

**Issue by VMohinder** [intel-isl/Open3D-PointNet2-Semantic3D#78]
Processing: bildstein_station1_xyz_intensity_rgb
Num points: 29697591
Num points after 0-skip: 9476296
Traceback (most recent call last):
  File "downsample.py", line 97, in <module>
    voxel_size,
  File "downsample.py", line 49, in down_sample
    sparse_pcd, cubics_ids = open3d.voxel_down_sample_and_trace(
**AttributeError: module 'open3d' has no attribute 'voxel_down_sample_and_trace'**

If I use 

sparse_pcd, cubics_ids = dense_pcd.voxel_down_sample_and_trace(voxel_size, min_bound, max_bound, False)

then

Processing: bildstein_station1_xyz_intensity_rgb
Num points: 29697591
Num points after 0-skip: 9476296
Traceback (most recent call last):
  File "downsample.py", line 100, in <module>
    voxel_size,
  File "downsample.py", line 53, in down_sample
    sparse_pcd, cubics_ids = dense_pcd.voxel_down_sample_and_trace(voxel_size, min_bound, max_bound, False)
**ValueError: too many values to unpack (expected 2)**

But if I use:

sparse_pcd = cubics_idsdense_pcd.voxel_down_sample_and_trace(voxel_size, min_bound, max_bound, False)

it works, but I'm not sure were **cubics_ids** are stored.

**Comment by VMohinder** [comment]
It seems that **cubics_ids** is stored in **sparse_pcd[1]**.

**Comment by rekharchandran** [comment]
sparse_pcd, cubics_ids, some_list = open3d.geometry.PointCloud.voxel_down_sample_and_trace(pcd, voxel_size, min_bound, max_bound, approximate_class=False) this works for me
